
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - events
  - persistentvolumeclaims
  - pods
  - secrets
  - services
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - get
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - create
  - get
- apiGroups:
  - nginx.tsuru.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - waf.arthurcgc.waf-operator
  resources:
  - wafplans
  - wafs
  verbs:
  - '*'
- apiGroups:
  - waf.arthurcgc.waf-operator
  resources:
  - wafplans/status
  - wafs/status
  verbs:
  - get
  - patch
  - update
