# permissions for end users to view wafs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: waf-viewer-role
rules:
- apiGroups:
  - waf.arthurcgc.waf-operator
  resources:
  - wafs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - waf.arthurcgc.waf-operator
  resources:
  - wafs/status
  verbs:
  - get
