# permissions for end users to edit wafplans.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wafplan-editor-role
rules:
- apiGroups:
  - waf.arthurcgc.waf-operator
  resources:
  - wafplans
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - waf.arthurcgc.waf-operator
  resources:
  - wafplans/status
  verbs:
  - get
