# permissions for end users to view wafplans.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wafplan-viewer-role
rules:
- apiGroups:
  - waf.arthurcgc.waf-operator
  resources:
  - wafplans
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - waf.arthurcgc.waf-operator
  resources:
  - wafplans/status
  verbs:
  - get
