apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: waf-operator-system
  name: waf-api
spec:
  selector:
    matchLabels:
      app: waf-api
  replicas: 2
  template:
    metadata:
      labels:
        app: waf-api
    spec:
      serviceAccountName: waf-api-service-account
      containers:
      - name: waf-api
        image: arthurcgc/waf:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: waf-operator-system
  name: waf-api
spec:
  type: NodePort
  selector:
    app: waf-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
