
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: waf-api-role
rules:
- apiGroups:
  - waf.arthurcgc.waf-operator
  resources:
  - wafplans
  - wafs
  verbs:
  - '*'
- apiGroups:
  - waf.arthurcgc.waf-operator
  resources:
  - wafplans/status
  - wafs/status
  verbs:
  - get
  - patch
  - update
